export const SET_TABLE_COLUMN_PREFRENCES = 'SET_TABLE_COLUMN_PREFRENCES';
export const SET_DEFAULT_FILTER_CONFIG_FLAG = 'SET_DEFAULT_FILTER_CONFIG_FLAG';
export const SET_IS_SIDE_PANEL_EXPANDED = 'SET_IS_SIDE_PANEL_EXPANDED';