export const SET_DASHBOARD_LOADER = 'SET_DASHBOARD_LOADER';
export const SET_DASHBOARD_FILTER = 'SET_DASHBOARD_FILTER';
export const FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA';
export const SET_DASHBOARD_ERROR = 'SET_DASHBOARD_ERROR'; 